# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Harvest-Business' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Harvest-Business
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'GoogleSignIn'
  pod 'Firebase/Storage'
  pod 'FirebaseUI/Storage'
  pod 'GeoFire/Utils'
  pod 'Firebase/Functions'
  pod 'MessageKit'
  pod 'NVActivityIndicatorView'
  # Stripe API
  pod 'Stripe'
  
  target 'Harvest-BusinessTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Harvest-BusinessUITests' do
    # Pods for testing
  end

end
